### ISSUE TITLE
P3F GetFieldID patch crash

### ISSUE THREAD

**Issue by spreggie** [Tupelov/Game-Patches#2]
This doesn't seem to work on a latest nightly PCSX2 build and crashes during booting ISO. If I use PCSX2 ver. 1.6.0 it works normally. I believe this is needed for your Persona 3 FES mod menu, but without this, I can't for example select anything from "Facilities" - after selecting game just freezes.

**Comment by epic-bruh-moment** [comment]
Replace every instance of 0x with 00, the new builds had a regression that messed with cheats.

**Comment by spreggie** [comment]
> Replace every instance of 0x with 00, the new builds had a regression that messed with cheats.

Woah, I was that close. While I was messing with it, I tried this, but instead of 0x I replaced every 0xa.. Anyway, thanks!
